# Generated by Django 4.1.5 on 2023-10-16 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0011_courses_course_institute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_deliverables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('attendance_date', models.DateField()),
                ('contents_covered', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.courses')),
                ('course_del', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_deliverables.coursedeliverables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_staff', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_student', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
