# Generated by Django 4.1.5 on 2023-11-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student_attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='student_attendance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_details_created_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_details', to=settings.AUTH_USER_MODEL)),
                ('student_attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stud_attendance_details', to='student_attendance.student_attendance')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_details_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
