# Generated by Django 4.1.5 on 2023-11-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_student_attendance_academic_session_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student_attendance_details',
            constraint=models.UniqueConstraint(fields=('student_attendance', 'student'), name='unique_student_attendace_and_student'),
        ),
    ]
