# Generated by Django 4.1.5 on 2023-11-21 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_attendance', '0004_student_attendance_details_unique_student_attendace_and_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='staff',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stud_attendance_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
