# Generated by Django 4.1.5 on 2023-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0007_remove_student_attendance_attendance_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='student_attendance',
            name='attendance_time',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='attendance_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
